# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81943bbfd047ceb818a7118583c2545cb50e104db3fcfb3d45ad2bd10e12ea0561976e072ecba26ed1aaea803626e55be25b6f3f6c4bf3f7b43eddc83bcd0d5d

test:
  secret_key_base: cdaa3800fe33424e446bc2dc79cebaa3c1c71ca05ea011b0dc0000f1cc3b738bd32bb8688223b4a460102519fea2c2c09076297cb1bdc5fb4bcf57420011e510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
